services:
  redis:
    image: redis:7-alpine
    container_name: shrimpvid_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - shrimpvid_network

  worker:
    build: .
    container_name: shrimpvid_worker
    command: taskiq worker src.tasks:broker
    environment:
      - PYTHONPATH=/app/src
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - COOKIES_FILE=${COOKIES_FILE:-/app/cookies.txt}
    depends_on:
      - redis
    networks:
      - shrimpvid_network
    restart: unless-stopped
    volumes:
      - ./cookies.txt:/app/cookies.txt

  bot:
    build: .
    container_name: shrimpvid_bot
    command: python src/main.py
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_HOST=${REDIS_HOST:-redis}
    depends_on:
      - redis
    networks:
      - shrimpvid_network
    restart: unless-stopped
    volumes:
      - ./cookies.txt:/app/cookies.txt:ro   # ro = read-only

networks:
  shrimpvid_network:
    driver: bridge

volumes:
  redis_data:
